In [4]:
import zipfile
import polars as pl
import io

zip_path = r'C:\Users\bened\Downloads\Archive (1).zip'

file_names = [
    'sample_user_note_traj',
    'sample_user_rating_traj',
    'sample_user_request_traj',
]

dataframes = {}
with zipfile.ZipFile(zip_path, 'r') as z:
    for name in file_names:
        matches = [f for f in z.namelist() if name in f and f.endswith('.parquet')]
        if not matches:
            print(f'Could not find {name}.parquet in zip')
            continue
        with z.open(matches[0]) as f:
            dataframes[name] = pl.read_parquet(io.BytesIO(f.read()))

for name, df in dataframes.items():
    print(f'\n{name} columns:')
    print(df.columns)

sample_user_note_traj columns:
['noteAuthorParticipantId', 'userMonth', 'sportsCount', 'diaries_&_daily_lifeCount', 'business_&_entrepreneursCount', 'science_&_technologyCount', 'news_&_social_concernCount', 'otherCount', 'calendarMonth', 'notesCreated', 'hitRate', 'hits', 'avgNoteFactor', 'avgNoteIntercept', 'topicsTargeted', 'avgRatingsEarned']

sample_user_rating_traj columns:
['raterParticipantId', 'userMonth', 'sportsRatedCount', 'diaries_&_daily_lifeRatedCount', 'business_&_entrepreneursRatedCount', 'science_&_technologyRatedCount', 'news_&_social_concernRatedCount', 'otherRatedCount', 'calendarMonth', 'notesRated', 'avgHelpfulFactor', 'avgNotHelpfulFactor', 'avgHelpfulIntercept', 'avgNotHelpfulIntercept', 'correctHelpfuls', 'correctNotHelpfuls', 'posFactorRatedHelpful', 'posFactorRatedNotHelpful', 'negFactorRatedHelpful', 'negFactorRatedNotHelpful', 'pctCorrectPosFactorHelpful', 'pctCorrectPosFactorNotHelpful', 'pctCorrectNegFactorHelpful', 'pctCorrectNegFactorNotHelpful', 'pctHelpfulRatingsCorrect', 'pctNotHelpfulRatingsCorrect', 'uniqueDaysRated', 'avgPostsRatedPerDay', 'uniqueTopicsRated', 'antiDemNNRatings', 'proDemNNRatings', 'proDemNNNRatings', 'antiDemNNNRatings', 'antiRepNNRatings', 'proRepNNRatings', 'proRepNNNRatings', 'antiRepNNNRatings', 'overallAccuracy', 'helpfulNotHelpfulFactorDiff', 'helpfulNotHelpfulInterceptDiff', 'proDemRatings', 'antiDemRatings', 'proRepRatings', 'antiRepRatings']

sample_user_request_traj columns:
['requesterParticipantId', 'userMonth', 'calendarMonth', 'requestsMade', 'numRequestsResultingInCrh', 'numRequestsResultingInNote', 'pctRequestResultedInNote', 'pctRequestResultedInCrh']

In [5]:
join_keys = ["userId", "userMonth", "calendarMonth"]

notes = dataframes["sample_user_note_traj"].rename({"noteAuthorParticipantId": "userId"})
ratings = dataframes["sample_user_rating_traj"].rename({"raterParticipantId": "userId"})
requests = dataframes["sample_user_request_traj"].rename({"requesterParticipantId": "userId"})

master = (
    notes
    .join(ratings, on=join_keys, how="full", coalesce=True)
    .join(requests, on=join_keys, how="full", coalesce=True)
    .sort(["userId", "userMonth"])
)

print(master.shape)
print(master.columns)
master.head()

(92281, 62)
['userId', 'userMonth', 'sportsCount', 'diaries_&_daily_lifeCount', 'business_&_entrepreneursCount', 'science_&_technologyCount', 'news_&_social_concernCount', 'otherCount', 'calendarMonth', 'notesCreated', 'hitRate', 'hits', 'avgNoteFactor', 'avgNoteIntercept', 'topicsTargeted', 'avgRatingsEarned', 'sportsRatedCount', 'diaries_&_daily_lifeRatedCount', 'business_&_entrepreneursRatedCount', 'science_&_technologyRatedCount', 'news_&_social_concernRatedCount', 'otherRatedCount', 'notesRated', 'avgHelpfulFactor', 'avgNotHelpfulFactor', 'avgHelpfulIntercept', 'avgNotHelpfulIntercept', 'correctHelpfuls', 'correctNotHelpfuls', 'posFactorRatedHelpful', 'posFactorRatedNotHelpful', 'negFactorRatedHelpful', 'negFactorRatedNotHelpful', 'pctCorrectPosFactorHelpful', 'pctCorrectPosFactorNotHelpful', 'pctCorrectNegFactorHelpful', 'pctCorrectNegFactorNotHelpful', 'pctHelpfulRatingsCorrect', 'pctNotHelpfulRatingsCorrect', 'uniqueDaysRated', 'avgPostsRatedPerDay', 'uniqueTopicsRated', 'antiDemNNRatings', 'proDemNNRatings', 'proDemNNNRatings', 'antiDemNNNRatings', 'antiRepNNRatings', 'proRepNNRatings', 'proRepNNNRatings', 'antiRepNNNRatings', 'overallAccuracy', 'helpfulNotHelpfulFactorDiff', 'helpfulNotHelpfulInterceptDiff', 'proDemRatings', 'antiDemRatings', 'proRepRatings', 'antiRepRatings', 'requestsMade', 'numRequestsResultingInCrh', 'numRequestsResultingInNote', 'pctRequestResultedInNote', 'pctRequestResultedInCrh']

shape: (5, 62)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ userId    ┆ userMonth ┆ sportsCou ┆ diaries_& ┆ … ┆ numReques ┆ numReques ┆ pctReques ┆ pctReque │
│ ---       ┆ ---       ┆ nt        ┆ _daily_li ┆   ┆ tsResulti ┆ tsResulti ┆ tResulted ┆ stResult │
│ str       ┆ i32       ┆ ---       ┆ feCount   ┆   ┆ ngInCrh   ┆ ngInNote  ┆ InNote    ┆ edInCrh  │
│           ┆           ┆ u32       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆ u32       ┆   ┆ u32       ┆ u32       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 000AE7795 ┆ 0         ┆ null      ┆ null      ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0      │
│ 5227AE8D5 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2CB70BA3F ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ B64…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 000C7AC0F ┆ 0         ┆ null      ┆ null      ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0      │
│ 2AE15FB6C ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 478257825 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ D41…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 0014F9BA3 ┆ 0         ┆ null      ┆ null      ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0      │
│ 34FB10689 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ F9D089BF4 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 791…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 00167DE21 ┆ 0         ┆ null      ┆ null      ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0      │
│ 1B4D41B0E ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 054EFD79A ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 977…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 00167DE21 ┆ 1         ┆ null      ┆ null      ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0      │
│ 1B4D41B0E ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 054EFD79A ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 977…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [7]:
# Fill nulls with 0 for activity columns (null = no activity of that type that month)
notes_col = pl.col("notesCreated").fill_null(0)
rated_col = pl.col("notesRated").fill_null(0)
reqs_col  = pl.col("requestsMade").fill_null(0)

classification = (
    pl.when(notes_col == 1).then(pl.lit("single_note_writer"))
    .when(notes_col.is_between(2, 9)).then(pl.lit("single_digit_writer"))
    .when(notes_col >= 10).then(pl.lit("double_digit_writer"))
    .when((notes_col == 0) & (rated_col == 1)).then(pl.lit("single_note_rater"))
    .when((notes_col == 0) & rated_col.is_between(2, 9)).then(pl.lit("single_digit_rater"))
    .when((notes_col == 0) & (rated_col >= 10)).then(pl.lit("double_digit_rater"))
    .when((notes_col == 0) & (rated_col == 0) & (reqs_col == 1)).then(pl.lit("single_post_requestor"))
    .when((notes_col == 0) & (rated_col == 0) & reqs_col.is_between(2, 9)).then(pl.lit("single_digit_requestor"))
    .when((notes_col == 0) & (rated_col == 0) & (reqs_col >= 10)).then(pl.lit("double_digit_requestor"))
    .otherwise(pl.lit("not_active"))
)

# multiple_categories: user was active in more than one of notes / ratings / requests
multi = (
    ((notes_col >= 1).cast(pl.Int8) +
     (rated_col >= 1).cast(pl.Int8) +
     (reqs_col  >= 1).cast(pl.Int8)) > 1
)

master_classified = master.with_columns([
    classification.alias("classification"),
    multi.alias("multiple_categories"),
])

print(master_classified["classification"].value_counts(sort=True))
master_classified

shape: (9, 2)
┌────────────────────────┬───────┐
│ classification         ┆ count │
│ ---                    ┆ ---   │
│ str                    ┆ u32   │
╞════════════════════════╪═══════╡
│ single_digit_rater     ┆ 29655 │
│ single_note_rater      ┆ 21890 │
│ single_post_requestor  ┆ 17126 │
│ double_digit_rater     ┆ 13646 │
│ single_digit_requestor ┆ 5358  │
│ single_note_writer     ┆ 2648  │
│ single_digit_writer    ┆ 1459  │
│ double_digit_requestor ┆ 415   │
│ double_digit_writer    ┆ 84    │
└────────────────────────┴───────┘

shape: (92_281, 64)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ userId    ┆ userMonth ┆ sportsCou ┆ diaries_& ┆ … ┆ pctReques ┆ pctReques ┆ classific ┆ multiple │
│ ---       ┆ ---       ┆ nt        ┆ _daily_li ┆   ┆ tResulted ┆ tResulted ┆ ation     ┆ _categor │
│ str       ┆ i32       ┆ ---       ┆ feCount   ┆   ┆ InNote    ┆ InCrh     ┆ ---       ┆ ies      │
│           ┆           ┆ u32       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ str       ┆ ---      │
│           ┆           ┆           ┆ u32       ┆   ┆ f64       ┆ f64       ┆           ┆ bool     │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 000AE7795 ┆ 0         ┆ null      ┆ null      ┆ … ┆ 0.0       ┆ 0.0       ┆ single_po ┆ false    │
│ 5227AE8D5 ┆           ┆           ┆           ┆   ┆           ┆           ┆ st_reques ┆          │
│ 2CB70BA3F ┆           ┆           ┆           ┆   ┆           ┆           ┆ tor       ┆          │
│ B64…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 000C7AC0F ┆ 0         ┆ null      ┆ null      ┆ … ┆ 0.0       ┆ 0.0       ┆ single_po ┆ false    │
│ 2AE15FB6C ┆           ┆           ┆           ┆   ┆           ┆           ┆ st_reques ┆          │
│ 478257825 ┆           ┆           ┆           ┆   ┆           ┆           ┆ tor       ┆          │
│ D41…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 0014F9BA3 ┆ 0         ┆ null      ┆ null      ┆ … ┆ 0.0       ┆ 0.0       ┆ single_po ┆ false    │
│ 34FB10689 ┆           ┆           ┆           ┆   ┆           ┆           ┆ st_reques ┆          │
│ F9D089BF4 ┆           ┆           ┆           ┆   ┆           ┆           ┆ tor       ┆          │
│ 791…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 00167DE21 ┆ 0         ┆ null      ┆ null      ┆ … ┆ 0.0       ┆ 0.0       ┆ single_po ┆ false    │
│ 1B4D41B0E ┆           ┆           ┆           ┆   ┆           ┆           ┆ st_reques ┆          │
│ 054EFD79A ┆           ┆           ┆           ┆   ┆           ┆           ┆ tor       ┆          │
│ 977…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 00167DE21 ┆ 1         ┆ null      ┆ null      ┆ … ┆ 0.0       ┆ 0.0       ┆ single_po ┆ false    │
│ 1B4D41B0E ┆           ┆           ┆           ┆   ┆           ┆           ┆ st_reques ┆          │
│ 054EFD79A ┆           ┆           ┆           ┆   ┆           ┆           ┆ tor       ┆          │
│ 977…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ FFF473DD9 ┆ 19        ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ single_no ┆ false    │
│ 05D41503C ┆           ┆           ┆           ┆   ┆           ┆           ┆ te_rater  ┆          │
│ F2EF95C6B ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 3AF…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ FFF473DD9 ┆ 20        ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ single_no ┆ false    │
│ 05D41503C ┆           ┆           ┆           ┆   ┆           ┆           ┆ te_rater  ┆          │
│ F2EF95C6B ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 3AF…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ FFF473DD9 ┆ 25        ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ single_di ┆ false    │
│ 05D41503C ┆           ┆           ┆           ┆   ┆           ┆           ┆ git_rater ┆          │
│ F2EF95C6B ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 3AF…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ FFFEA897F ┆ 0         ┆ null      ┆ null      ┆ … ┆ 0.0       ┆ 0.0       ┆ single_di ┆ false    │
│ AE26B6664 ┆           ┆           ┆           ┆   ┆           ┆           ┆ git_reque ┆          │
│ E59ED1C99 ┆           ┆           ┆           ┆   ┆           ┆           ┆ stor      ┆          │
│ 63A…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ FFFEA897F ┆ 2         ┆ null      ┆ null      ┆ … ┆ 0.0       ┆ 0.0       ┆ single_po ┆ false    │
│ AE26B6664 ┆           ┆           ┆           ┆   ┆           ┆           ┆ st_reques ┆          │
│ E59ED1C99 ┆           ┆           ┆           ┆   ┆           ┆           ┆ tor       ┆          │
│ 63A…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘